/*
 * Copyright (C) 2018 Volodymyr Kryachko
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef G2DG_OUT_EDGE_ITERATOR_HPP
#define G2DG_OUT_EDGE_ITERATOR_HPP

#include <boost/iterator/iterator_facade.hpp>

#include "grid2d_graph_basic.hpp"

namespace g2dg {
    template <typename row_type, typename column_type, row_type rows_num, column_type columns_num>
    class g2dg_out_edge_iterator : public boost::iterator_facade <
        g2dg_out_edge_iterator<row_type,column_type,rows_num,columns_num>,
        g2dg_edge,
        boost::forward_traversal_tag,
        g2dg_edge const>
    {
    public:
        g2dg_out_edge_iterator() : m_base(std::make_pair(vertex(),invalid_direction))
        { }

        explicit g2dg_out_edge_iterator(const g2dg_out_edge_iterator_base& data)
            : m_base(data)
        { }

        explicit g2dg_out_edge_iterator(const vertex& v) :
            m_base(std::make_pair(v, first_direction))
        {
            vertex adjacent = get_adjacent(m_base.first, m_base.second);
            if (!is_legal_vertex<rows_num, columns_num>(adjacent)) increment();
        }

    private:
        friend class boost::iterator_core_access;

        void increment() {
            if (m_base.second > last_direction)
                return;

            while (++m_base.second <= last_direction) {
                vertex adjacent = get_adjacent(m_base.first, m_base.second);

                if (is_legal_vertex<rows_num, columns_num>(adjacent))
                    break;
            }
        }

        void decrement() {
            if (m_base.second <= first_direction)
                return;

            do {
                --m_base.second;
                vertex adjacent = get_adjacent(m_base.first, m_base.second);

                if (is_legal_vertex<rows_num, columns_num>(adjacent))
                    break;

            } while (m_base.second <= first_direction);
        }

        g2dg_edge const dereference() const {
            return
                std::make_pair( m_base.first, get_adjacent(m_base.first, m_base.second));
        }

        bool equal(g2dg_out_edge_iterator const& x) const
        { return x.m_base == this->m_base; }

        g2dg_out_edge_iterator_base m_base;

    };
} // namespace g2dg
#endif // G2DG_OUT_EDGE_ITERATOR_HPP
